import { Inter } from "next/font/google";
import "../globals.css";
import Provider from "../components/Provider";
import Navbar from "../components/์NavBar";
import Container from "../components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {" "}
          <Navbar />
          <Container>
            {children} 
            </Container>  
        </Provider>
      </body>
    </html>
  );
}
